### ISSUE TITLE
How does cookie code work

### ISSUE THREAD

**Issue by uler3161** [mogthesprog/jwtauthenticator#23]
I'm having trouble setting up jwtauthenticator to authenticate my user. We simply want to allow the user to log into our web app, then be able to hit a link that takes them to Jupyterhub without having to log into there.

I've asked some questions on security.stackexchange asking what I need to do, but I don't seem to have any responses that help. For reference, here is that conversation: [Understanding JWT and SSO](https://security.stackexchange.com/questions/214876/understanding-jwt-and-sso)

In a nutshell, here's what we've tried:

1. Submitting Authorization header with JWT token... Works in PostMan, but we can't open the Jupyter link in a new tab, as we can't submit headers.

2. GET request with JWT token as query param. This works, but I believe there are security issues.

3. POST equivalent of GET. I believe this would be secure, as the POST variables are encrypted when using HTTPS. However, it doesn't appear jwtauthenticator allows POST.

4. Set XSRF-TOKEN cookie with the value being the JWT token string. Both web app and Jupyterhub are subdomains of the same domain. Domain is set on the cookie, with path "/". Setting the cookie seems like the way to make this work, but it doesn't seem to be reading the cookie. DevTools shows the cookie is there when at the Jupyterhub site.

I was hoping this would be easier than it seems to be. All we are trying to do is provide our users a link to Jupyterhub that doesn't require login. Can someone tell me if I'm on the right track to implement that with the cookie option? And if so, what could be wrong. Thanks.

**Comment by uler3161** [comment]
Never mind. I wasn't the one setting up the server and apparently whoever did had a very old version of jwtauthenticator. Odd, since we only recently went to set it up, so I wouldn't have expected an old version. Not sure where this old version came from. But it seems to work, so I'm happy.

**Comment by ansoncsh** [comment]
Hi @uler3161, I exactly have the same question as you. I am using query parameters but it is not a good idea for security reasons.
Would you mind to share how you finally solve it?

Many thanks!

**Comment by uler3161** [comment]
We first made sure we had the latest version of jwtauthenticator (which was our main issue).

Our code basically calls an endpoint which will set the proper cookie before returning. In our case, we also return the url to our Jupyter server which the browser will then navigate to instead of hard-coding it into the web app.

    var cookie = new CookieHeaderValue("XSRF-TOKEN", $"{BuildJWTToken()}")
    {
        HttpOnly = true,
        Secure = true,
        Domain = GetJupyterDomain(),
        Path = "/"
    };

    var resp = new HttpResponseMessage
    {
        StatusCode = HttpStatusCode.OK,
        Content = new StringContent(GetJupyterUrl())
    };
    resp.Headers.AddCookies(new[] { cookie });
    return resp;


And we use [This Library](https://github.com/jwt-dotnet/jwt) to generate a JWT token string (which we do in the BuildJWTToken method).

I think we also had to have our web app and our Jupyter server mapped to the same Domain for this to work. Basically whatever you can set up in order for the XSRF-TOKEN Cookie to be seen in both the web app and in Jupyter.

**Comment by ansoncsh** [comment]
Many thanks for the sharing. I forgot to use the same domain. It works fine.

BTW, have you handled the logout case?
When I access to Jupyter with another token in XSRF-TOKEN cookie without logging out the previous account, it shows 403 Forbidden error OR the project of the previous account.

**Comment by uler3161** [comment]
We are having some logout issues, specifically seeing projects from the previous account. It seemed to work fine for me to use the logout link in Jupyter. However, another person on my team says the logout link seems to not work reliably. We are planning to find a way to force a logout before the next login, but we haven't worked on it yet.

**Comment by ansoncsh** [comment]
Thank you so much for the sharing!
