### ISSUE TITLE
Cannot seem to use this with Zero to JupyterHub

### ISSUE THREAD

**Issue by stevegore** [mogthesprog/jwtauthenticator#26]
Trying to use this as a custom authenticator for [Zero to JupyterHub with Kubernetes](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/).

As mentioned in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1506, I cannot seem to get this class to be recognised by JupyterHub: 

```
[C 2019-12-02 05:28:18.719 JupyterHub application:90] Bad config encountered during initialization:
[C 2019-12-02 05:28:18.719 JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7f346f7e50f0> instance must be a type, but 'jwtauthenticator.jwtauthenticator.JSONWebTokenLocalAuthenticator' could not be imported
```

Any suggestions?

**Comment by allanitis** [comment]
What was the solution? Am getting the same problem
