### ISSUE TITLE
FileNotFoundError open(signing_certificate, 'r')

### ISSUE THREAD

**Issue by mjuliadlima** [mogthesprog/jwtauthenticator#4]
Hi.

I apologise for my beginner question. I configured my Jupyterhub installation to use the JWTAuthenticator. In my test, when I make a request to http://localhost:8000/hub/login, passing the token in the request header ("Authorization"), I get the following error:
    Traceback (most recent call last):
      File "/anaconda/lib/python3.6/site-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/anaconda/lib/python3.6/site-packages/jwtauthenticator/jwtauthenticator.py", line 22, in get
        claims = self.verify_jwt_with_claims(auth_header_content, signing_certificate, audience)
      File "/anaconda/lib/python3.6/site-packages/jwtauthenticator/jwtauthenticator.py", line 37, in verify_jwt_with_claims
        with open(signing_certificate, 'r') as rsa_public_key_file:
    FileNotFoundError: [Errno 2] No such file or directory: '' 

I have set the configuration bellow in the jupyterhub_config.py:

c.JupyterHub.authenticator_class = 'jwtauthenticator.jwtauthenticator.JSONWebTokenAuthenticator'
c.LocalAuthenticator.signing_certificate = 'public.pem' 

Thanks for any help.

**Comment by harschware** [comment]
try a fully qualified path.  e.g.
```
c.LocalAuthenticator.signing_certificate = '/root/public.pem'
```

**Comment by mogthesprog** [comment]
Hello! As @harschware says, fully qualified path should do it. I'll close now, but reopen if you're issue persists.

Cheers
