### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Ranfer** [mogthesprog/jwtauthenticator#5]
Hi, I'm getting this error when trying to run JupyterHub, could it be a missing configuration step? or do you have any other idea? thanks...

JupyterHub application:91] The 'authenticator_class' trait of <jupyterhub.app.JupyterHub object at 0x7fb42aff2198> instance must be a type, but 'jwtauthenticator.jwtauthenticator.JSONWebTokenAuthenticator' could not be imported

**Comment by Ranfer** [comment]
Sorry it was a problem with my Ubuntu config.

**Comment by stevegore** [comment]
What was the problem with your Ubuntu config? I'm getting the same error.
